# This file was generated by GoReleaser. DO NOT EDIT.
cask "atomic-cli" do
  version "1.2.4-rc.14"

  on_macos do
    on_intel do
      sha256 "286de642026b51373ebe5d03841a5ee3280c68810b64a00d6db893ecafe37a02"
      url "https://github.com/libatomic/atomic-cli/releases/download/v#{version}/atomic-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "54c5d4676aeefa791f49a8dd9ae80ea59183bf056acb11887b8e796d33185ba7"
      url "https://github.com/libatomic/atomic-cli/releases/download/v#{version}/atomic-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da04498b946302a2256791209b5c758105d836be6361ffbde2a4ded1314a2d06"
      url "https://github.com/libatomic/atomic-cli/releases/download/v#{version}/atomic-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "688400a6fc3fa62295b59a93ea093dfb7204e811cf046342eef823f958ace977"
      url "https://github.com/libatomic/atomic-cli/releases/download/v#{version}/atomic-cli_Linux_arm64.tar.gz"
    end
  end

  name "atomic-cli"
  desc "A command-line tool for Atomic"
  homepage "https://github.com/libatomic/atomic-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atomic-cli"

  # No zap stanza required

end
