# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtomicCli < Formula
  desc "A command-line tool for Atomic"
  homepage "https://github.com/libatomic/atomic-cli"
  version "2.0.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libatomic/atomic-cli/releases/download/v2.0.0-rc.1/atomic-cli_Darwin_x86_64.tar.gz"
      sha256 "ece67a165553564377a91b95ffa6c75a8fdd6e1d8a5df23e5ad59f71375ce578"

      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libatomic/atomic-cli/releases/download/v2.0.0-rc.1/atomic-cli_Darwin_arm64.tar.gz"
      sha256 "797805e0224021c05cc8132a0037a48933f7a8173814479637a3e6c24f8d4bb5"

      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libatomic/atomic-cli/releases/download/v2.0.0-rc.1/atomic-cli_Linux_x86_64.tar.gz"
      sha256 "72734fe07ec193f692b3377901856420b8310273cf97c7f21c14671f1c874de5"
      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libatomic/atomic-cli/releases/download/v2.0.0-rc.1/atomic-cli_Linux_arm64.tar.gz"
      sha256 "f3b7ede0f62631b7bccdfd48900740385dbe6196f49d78a82ffcc8b1d3d6125c"
      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
  end

  test do
    output = shell_output("#{bin}/atomic-cli --help", 2)
    assert_match "atomic", output
  end
end
