# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class AtomicCli < Formula
  desc "A command-line tool for Atomic"
  homepage "https://github.com/libatomic/atomic-cli"
  version "1.2.0-beta.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libatomic/atomic-cli/releases/download/v1.2.0-beta.9/atomic-cli_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "88d4162798c001735d90ef5696b31c9faf28459aac725b2a172d01c0bf20866f"

      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libatomic/atomic-cli/releases/download/v1.2.0-beta.9/atomic-cli_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "26b3d533a8baf17754f6d12ab999dc7356518fb8724e117ad2068fbceef08ac8"

      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libatomic/atomic-cli/releases/download/v1.2.0-beta.9/atomic-cli_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "aa517717554a5788793e6cf9346f5d79973005698bef71e0ae382a48f5e97ea4"
      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libatomic/atomic-cli/releases/download/v1.2.0-beta.9/atomic-cli_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "08c8d8efc8d6fac6e8d5e154954234159f4dd4c998a71230483cc129a3db5430"
      define_method(:install) do
        bin.install "atomic-cli"
      end
    end
  end

  test do
    output = shell_output("#{bin}/atomic-cli --help", 2)
    assert_match "atomic", output
  end
end
